#!/bin/sh
# Un comment and use set +e to ignore and set -e to enable 'exit on error control'
set +e
# Un comment the line below to help debug scripts by printing a trace of the script commands
#set -x
# PX4FMU startup script.
#
# NOTE: environment variable references:
#    If the dollar sign ('$') is followed by a left bracket ('{') then the
#    variable name is terminated with the right bracket character ('}').
#    Otherwise, the variable name goes to the end of the argument.
#
#
# NOTE: COMMENT LINES ARE REMOVED BEFORE STORED IN ROMFS.
#
#------------------------------------------------------------------------------

#
# Set default paramter values.
# Do not add intra word spaces
# it wastes flash
#

#
# Mount the procfs.
#
#mount -t procfs /proc

echo "Nuttx Init Script"
echo "-----------------"



echo "uorb initialization"
uorb start


echo "mount /dev/mmcsd0 on /fs/microsd"
#
# Mount the mmcsd fatfs.
#
mount -t vfat /dev/mmcsd0 /fs/microsd
