language: cpp

sudo: required

branches:
  only:
  - master

os: linux
compiler: gcc
dist: bionic 

jobs:
  include:
  - stage: setup_env
    script: 
      - cd Tools/setup
      - ./ubuntu.sh
  
  - stage: build
    script:
      - cmake --configure .
      - cmake --build .
      - cd build
      - make all
    
  
script:
  -   echo "hello from travis "