language: cpp

sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker pull tito97sp/project_template-dev-base-bionic:1.0.0 
  - docker run -d -p 127.0.0.1:80:4567 tito97sp/project_template-dev-base-bionic:1.0.0 /bin/sh -c "cd /root/project_template-dev-base-bionic; bundle exec foreman start;"
  - docker ps -a
  - docker run tito97sp/project_template-dev-base-bionic:1.0.0 /bin/sh -c "cd /root/project_template-dev-base-bionic; bundle exec foreman start;"

jobs:
  include:
  - stage: setup_env
    script: 
      - cd $TRAVIS_BUILD_DIR
      - cd Tools/setup
      - ./ubuntu.sh
      - cd $TRAVIS_BUILD_DIR
      - cmake --configure .
      - cmake --build .
    
  
script:
  -   echo "hello from travis "
