language: cpp

sudo: required

services:
  - docker

branches:
  only:
  - master

jobs:
  include:
  - stage: setup_env
    script: 
      - cd $TRAVIS_BUILD_DIR
      - cd Tools/setup
      - ./ubuntu.sh
      - cd $TRAVIS_BUILD_DIR
      - cmake --configure .
      - cmake --build .
    
  
script:
  -   echo "hello from travis "
