name: Nuttx Targets

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: tito97sp/project_template-dev-base-bionic:1.0.1
    strategy:
      matrix:
        config: [
          stm_nucleo_h743zi
          ]
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{secrets.ACCESS_TOKEN}}
    
    - name: setup_env
      run: ./Tools/setup/ubuntu.sh 

    - name: make ${{matrix.config}} 
      run: make ${{matrix.config}} NO_NINJA_BUILD=1
   
