name: Nuttx Targets

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    container: tito97sp/project_template-dev-base-bionic:1.0.1
    strategy:
      matrix:
        config: [
          all
          ]
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        
    - name: make ${{matrix.config}}
      run: |
        cmake --configure .
        make ${{matrix.config}}
   
